Common:
  verbose: False
  sub_frame_type: [3, 1, 1, 0, 0] #0:leg 1:arm 2:wheel 3:waist
  end_frame_name_in_urdf:
    [
      "waist_site",
      "left_arm_site",
      "right_arm_site",
      "left_foot_site",
      "right_foot_site",
    ]

Actual:
  active_joint_name: [
      ["idx01_body_yaw", "idx04_body_left_rod1", "idx05_body_right_rod1"], #waist
      [
        "idx06_arm_left_01",
        "idx07_arm_left_02",
        "idx08_arm_left_03",
        "idx09_arm_left_04",
        "idx10_arm_left_05",
        "idx14_01_left_wrist_rod_A_joint",
        "idx16_01_left_wrist_rod_B_joint",
      ], #left arm

      [
        "idx17_arm_right_01",
        "idx18_arm_right_02",
        "idx19_arm_right_03",
        "idx20_arm_right_04",
        "idx21_arm_right_05",
        "idx25_01_right_wrist_rod_A_joint",
        "idx27_01_right_wrist_rod_B_joint",
      ], #right arm

      [
        "idx28_leg_left_thigh_pitch",
        "idx29_leg_left_thigh_roll",
        "idx30_leg_left_thigh_yaw",
        "idx31_leg_left_shank",
        "idx32_01_left_toe_motorA",
        "idx34_01_left_toe_motorB",
      ], #left foot

      [
        "idx38_leg_right_thigh_pitch",
        "idx39_leg_right_thigh_roll",
        "idx40_leg_right_thigh_yaw",
        "idx41_leg_right_shank",
        "idx42_01_right_toe_motorA",
        "idx44_01_right_toe_motorB",
      ], #right foot
    ]
  active_joint_type: [
      ["revolute", "revolute", "revolute"], #waist
      [
        "revolute",
        "revolute",
        "revolute",
        "revolute",
        "revolute",
        "prismatic",
        "prismatic",
      ], #left arm
      [
        "revolute",
        "revolute",
        "revolute",
        "revolute",
        "revolute",
        "prismatic",
        "prismatic",
      ], #right arm
      ["revolute", "revolute", "revolute", "revolute", "revolute", "revolute"], #left leg
      ["revolute", "revolute", "revolute", "revolute", "revolute", "revolute"], #right leg
    ]

  passive_joint_name: [
      ["idx02_body_roll", "idx03_body"], #waist
      ["idx11_arm_left_06", "idx12_arm_left_07"], #left arm
      ["idx22_arm_right_06", "idx23_arm_right_07"], #right arm
      ["idx36_left_toe_pitch", "idx37_left_toe_roll"], #left foot
      ["idx46_right_toe_pitch", "idx47_right_toe_roll"], #right foot
    ]
  passive_joint_type:
    [
      ["revolute", "revolute"],
      ["revolute", "revolute"],
      ["revolute", "revolute"],
      ["revolute", "revolute"],
      ["revolute", "revolute"],
    ]

Sensor:
  joint_passive_sensor_name: [
      ["idx02_body_roll", "idx03_body"], #waist
      ["idx11_arm_left_06", "idx12_arm_left_07"], #left arm
      ["idx22_arm_right_06", "idx23_arm_right_07"], #right arm
      ["idx36_left_toe_pitch", "idx37_left_toe_roll"], #left foot
      ["idx46_right_toe_pitch", "idx47_right_toe_roll"], #right foot
    ]
  joint_passive_sensor_active_id: [
      [1, 2], # waist
      [5, 6], #left hand
      [5, 6], #right hand
      [4, 5], #left foot
      [4, 5], #right foot
    ]
  contact_sensor_name: [
      [], #waist
      [], #left hand
      [], #right hand
      [
        "foot_left_contact_toe_l",
        "foot_left_contact_toe_r",
        "foot_left_contact_heel_l",
        "foot_left_contact_heel_r",
      ], #left foot
      [
        "foot_right_contact_toe_l",
        "foot_right_contact_toe_r",
        "foot_right_contact_heel_l",
        "foot_right_contact_heel_r",
      ], #right foot
    ]

Logical:
  joint_locked_name: [
      ["idx01_body_yaw", "idx02_body_roll", "idx03_body"], #waist
      [
        "idx08_arm_left_03",
        "idx10_arm_left_05",
        "idx11_arm_left_06",
        "idx12_arm_left_07",
      ], #left arm

      [
        "idx19_arm_right_03",
        "idx21_arm_right_05",
        "idx22_arm_right_06",
        "idx23_arm_right_07",
      ], #right arm
      [],
      [],
    ]
  joint_locked_position: [[0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [], []]

  end_frame_site_name_in_urdf: [
      [], #waist
      [], #left hand
      [], #right hand
      [
        "left_foot_toe_left",
        "left_foot_toe_right",
        "left_foot_heel_left",
        "left_foot_heel_right",
      ], #left foot
      [
        "right_foot_toe_left",
        "right_foot_toe_right",
        "right_foot_heel_left",
        "right_foot_heel_right",
      ], #right foot
    ]

  end_frame_odometry_enable: [false, false, false, true, true]

  serial_joint_name: [
      ["idx01_body_yaw", "idx02_body_roll", "idx03_body"], #waist
      [
        "idx06_arm_left_01",
        "idx07_arm_left_02",
        "idx08_arm_left_03",
        "idx09_arm_left_04",
        "idx10_arm_left_05",
        "idx11_arm_left_06",
        "idx12_arm_left_07",
      ], #left arm
      [
        "idx17_arm_right_01",
        "idx18_arm_right_02",
        "idx19_arm_right_03",
        "idx20_arm_right_04",
        "idx21_arm_right_05",
        "idx22_arm_right_06",
        "idx23_arm_right_07",
      ], #right arm
      [
        "idx28_leg_left_thigh_pitch",
        "idx29_leg_left_thigh_roll",
        "idx30_leg_left_thigh_yaw",
        "idx31_leg_left_shank",
        "idx36_left_toe_pitch",
        "idx37_left_toe_roll",
      ], #left leg
      [
        "idx38_leg_right_thigh_pitch",
        "idx39_leg_right_thigh_roll",
        "idx40_leg_right_thigh_yaw",
        "idx41_leg_right_shank",
        "idx46_right_toe_pitch",
        "idx47_right_toe_roll",
      ], #right leg
    ]

  nominal_configuration:
    [
      [0, 0, 0],
      [1.57, 0.2, -1.57, -0.36, 0, 0, 0],
      [-1.57, -0.2, -1.57, 0.36, 0, 0, 0],
      [0.48891, 0.06213, -0.33853, 0.63204, -0.27224, 0],
      [-0.48891, -0.06213, 0.33853, 0.63204, -0.27224, 0],
    ]
